version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn install fabric8:build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - mvn fabric8:push -Ddocker.registry=${DOCKER_REGISTRY}