version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sh mvnw install fabric8:build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - sh mvnw fabric8:push -Ddocker.registry=${DOCKER_REGISTRY_PARAM}
artifacts:
  discard-paths: yes
  files:
    - env/docker-compose.yaml